channels:
  - conda-forge
  - bioconda
dependencies:
  - r-base=4.0
  - r-tidyverse
  - r-ggplot2
  - r-remotes
  - r-BiocManager
  #- bioconductor-Hiiragi2013
  #- bioconductor-biocinstaller 
BiocManager: 
  #- UCLouvain-CBIO/rWSBIM1322\
  - rWSBIM1322
