channels:
  - conda-forge
  - bioconda
dependencies:
  - r-base=4.0
  - r-tidyverse
  - r-ggplot2
  - r-remotes
  - bioconductor-Hiiragi2013
  - bioconductor-biocinstaller
biocManager: 
  - UCLouvain-CBIO/rWSBIM1322
